debug: true
data_root: ???
resolution: 512
dataloader_num_workers: 8
train_batch_size: 16
gradient_accumulation_steps: 1
pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
unet_model_path: ''
revision: null
loss_type: noise_matching
pred_type: epsilon
windows: 4
solving_steps: 8
support_cfg: true
cfg_sync: true
discrete_timesteps: -1
learning_rate: 8.0e-05
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 1000
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.0e-05
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
max_train_steps: 1000000
use_ema: true
gradient_checkpointing: false
mixed_precision: fp16
local_rank: -1
output_dir: _exps_/tmp
report_to: tensorboard
validation_steps: 100
val_steps: 8
val_cfg: 7.5
checkpointing_steps: 1000
checkpoints_total_limit: null
resume_from_checkpoint: null
total_batch_size: 16
